import {renderString} from "@awesome.me/webawesome/dist/ssr/render-string.js"

import "./polyfills.js"

// import "@awesome.me/webawesome-pro/dist/components/animated-image/animated-image.js"
// import "@awesome.me/webawesome-pro/dist/components/animation/animation.js"
// import "@awesome.me/webawesome-pro/dist/components/avatar/avatar.js"
// import "@awesome.me/webawesome-pro/dist/components/badge/badge.js"
// import "@awesome.me/webawesome-pro/dist/components/bar-chart/bar-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/breadcrumb-item/breadcrumb-item.js"
// import "@awesome.me/webawesome-pro/dist/components/breadcrumb/breadcrumb.js"
// import "@awesome.me/webawesome-pro/dist/components/bubble-chart/bubble-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/button-group/button-group.js"
// import "@awesome.me/webawesome-pro/dist/components/button/button.js"
// import "@awesome.me/webawesome-pro/dist/components/callout/callout.js"
// import "@awesome.me/webawesome-pro/dist/components/card/card.js"
// import "@awesome.me/webawesome-pro/dist/components/carousel-item/carousel-item.js"
// import "@awesome.me/webawesome-pro/dist/components/carousel/carousel.js"
// import "@awesome.me/webawesome-pro/dist/components/chart/chart.js"
// import "@awesome.me/webawesome-pro/dist/components/checkbox/checkbox.js"
// import "@awesome.me/webawesome-pro/dist/components/color-picker/color-picker.js"
// import "@awesome.me/webawesome-pro/dist/components/combobox/combobox.js"
// import "@awesome.me/webawesome-pro/dist/components/comparison/comparison.js"
// import "@awesome.me/webawesome-pro/dist/components/copy-button/copy-button.js"
// import "@awesome.me/webawesome-pro/dist/components/details/details.js"
// import "@awesome.me/webawesome-pro/dist/components/dialog/dialog.js"
// import "@awesome.me/webawesome-pro/dist/components/divider/divider.js"
// import "@awesome.me/webawesome-pro/dist/components/doughnut-chart/doughnut-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/drawer/drawer.js"
// import "@awesome.me/webawesome-pro/dist/components/dropdown-item/dropdown-item.js"
// import "@awesome.me/webawesome-pro/dist/components/dropdown/dropdown.js"
// import "@awesome.me/webawesome-pro/dist/components/file-input/file-input.js"
// import "@awesome.me/webawesome-pro/dist/components/format-bytes/format-bytes.js"
// import "@awesome.me/webawesome-pro/dist/components/format-date/format-date.js"
// import "@awesome.me/webawesome-pro/dist/components/format-number/format-number.js"
// import "@awesome.me/webawesome-pro/dist/components/icon/icon.js"
// import "@awesome.me/webawesome-pro/dist/components/include/include.js"
// import "@awesome.me/webawesome-pro/dist/components/input/input.js"
// import "@awesome.me/webawesome-pro/dist/components/intersection-observer/intersection-observer.js"
// import "@awesome.me/webawesome-pro/dist/components/line-chart/line-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/markdown/markdown.js"
// import "@awesome.me/webawesome-pro/dist/components/mutation-observer/mutation-observer.js"
// import "@awesome.me/webawesome-pro/dist/components/number-input/number-input.js"
// import "@awesome.me/webawesome-pro/dist/components/option/option.js"
// import "@awesome.me/webawesome-pro/dist/components/page/page.js"
// import "@awesome.me/webawesome-pro/dist/components/pie-chart/pie-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/polar-area-chart/polar-area-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/popover/popover.js"
// import "@awesome.me/webawesome-pro/dist/components/popup/popup.js"
// import "@awesome.me/webawesome-pro/dist/components/progress-bar/progress-bar.js"
// import "@awesome.me/webawesome-pro/dist/components/progress-ring/progress-ring.js"
// import "@awesome.me/webawesome-pro/dist/components/qr-code/qr-code.js"
// import "@awesome.me/webawesome-pro/dist/components/radar-chart/radar-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/radio-group/radio-group.js"
// import "@awesome.me/webawesome-pro/dist/components/radio/radio.js"
// import "@awesome.me/webawesome-pro/dist/components/rating/rating.js"
// import "@awesome.me/webawesome-pro/dist/components/relative-time/relative-time.js"
// import "@awesome.me/webawesome-pro/dist/components/resize-observer/resize-observer.js"
// import "@awesome.me/webawesome-pro/dist/components/scatter-chart/scatter-chart.js"
// import "@awesome.me/webawesome-pro/dist/components/scroller/scroller.js"
// import "@awesome.me/webawesome-pro/dist/components/select/select.js"
// import "@awesome.me/webawesome-pro/dist/components/skeleton/skeleton.js"
// import "@awesome.me/webawesome-pro/dist/components/slider/slider.js"
// import "@awesome.me/webawesome-pro/dist/components/sparkline/sparkline.js"
// import "@awesome.me/webawesome-pro/dist/components/spinner/spinner.js"
// import "@awesome.me/webawesome-pro/dist/components/split-panel/split-panel.js"
// import "@awesome.me/webawesome-pro/dist/components/switch/switch.js"
// import "@awesome.me/webawesome-pro/dist/components/tab-group/tab-group.js"
// import "@awesome.me/webawesome-pro/dist/components/tab-panel/tab-panel.js"
// import "@awesome.me/webawesome-pro/dist/components/tab/tab.js"
// import "@awesome.me/webawesome-pro/dist/components/tag/tag.js"
// import "@awesome.me/webawesome-pro/dist/components/textarea/textarea.js"
// import "@awesome.me/webawesome-pro/dist/components/toast-item/toast-item.js"
// import "@awesome.me/webawesome-pro/dist/components/toast/toast.js"
// import "@awesome.me/webawesome-pro/dist/components/tooltip/tooltip.js"
// import "@awesome.me/webawesome-pro/dist/components/tree-item/tree-item.js"
// import "@awesome.me/webawesome-pro/dist/components/tree/tree.js"
// import "@awesome.me/webawesome-pro/dist/components/video-playlist/video-playlist.js"
// import "@awesome.me/webawesome-pro/dist/components/video/video.js"
// import "@awesome.me/webawesome-pro/dist/components/zoomable-frame/zoomable-frame.js"

import "@awesome.me/webawesome/dist/components/animated-image/animated-image.js"
import "@awesome.me/webawesome/dist/components/animation/animation.js"
import "@awesome.me/webawesome/dist/components/avatar/avatar.js"
import "@awesome.me/webawesome/dist/components/badge/badge.js"
import "@awesome.me/webawesome/dist/components/breadcrumb-item/breadcrumb-item.js"
import "@awesome.me/webawesome/dist/components/breadcrumb/breadcrumb.js"
import "@awesome.me/webawesome/dist/components/button-group/button-group.js"
import "@awesome.me/webawesome/dist/components/button/button.js"
import "@awesome.me/webawesome/dist/components/callout/callout.js"
import "@awesome.me/webawesome/dist/components/card/card.js"
import "@awesome.me/webawesome/dist/components/carousel-item/carousel-item.js"
import "@awesome.me/webawesome/dist/components/carousel/carousel.js"
import "@awesome.me/webawesome/dist/components/checkbox/checkbox.js"
import "@awesome.me/webawesome/dist/components/color-picker/color-picker.js"
import "@awesome.me/webawesome/dist/components/comparison/comparison.js"
import "@awesome.me/webawesome/dist/components/copy-button/copy-button.js"
import "@awesome.me/webawesome/dist/components/details/details.js"
import "@awesome.me/webawesome/dist/components/dialog/dialog.js"
import "@awesome.me/webawesome/dist/components/divider/divider.js"
import "@awesome.me/webawesome/dist/components/drawer/drawer.js"
import "@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js"
import "@awesome.me/webawesome/dist/components/dropdown/dropdown.js"
import "@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js"
import "@awesome.me/webawesome/dist/components/format-date/format-date.js"
import "@awesome.me/webawesome/dist/components/format-number/format-number.js"
import "@awesome.me/webawesome/dist/components/icon/icon.js"
import "@awesome.me/webawesome/dist/components/include/include.js"
import "@awesome.me/webawesome/dist/components/input/input.js"
import "@awesome.me/webawesome/dist/components/intersection-observer/intersection-observer.js"
import "@awesome.me/webawesome/dist/components/markdown/markdown.js"
import "@awesome.me/webawesome/dist/components/mutation-observer/mutation-observer.js"
import "@awesome.me/webawesome/dist/components/number-input/number-input.js"
import "@awesome.me/webawesome/dist/components/option/option.js"
import "@awesome.me/webawesome/dist/components/page/page.js"
import "@awesome.me/webawesome/dist/components/popover/popover.js"
import "@awesome.me/webawesome/dist/components/popup/popup.js"
import "@awesome.me/webawesome/dist/components/progress-bar/progress-bar.js"
import "@awesome.me/webawesome/dist/components/progress-ring/progress-ring.js"
import "@awesome.me/webawesome/dist/components/qr-code/qr-code.js"
import "@awesome.me/webawesome/dist/components/radio-group/radio-group.js"
import "@awesome.me/webawesome/dist/components/radio/radio.js"
import "@awesome.me/webawesome/dist/components/rating/rating.js"
import "@awesome.me/webawesome/dist/components/relative-time/relative-time.js"
import "@awesome.me/webawesome/dist/components/resize-observer/resize-observer.js"
import "@awesome.me/webawesome/dist/components/scroller/scroller.js"
import "@awesome.me/webawesome/dist/components/select/select.js"
import "@awesome.me/webawesome/dist/components/skeleton/skeleton.js"
import "@awesome.me/webawesome/dist/components/slider/slider.js"
import "@awesome.me/webawesome/dist/components/spinner/spinner.js"
import "@awesome.me/webawesome/dist/components/split-panel/split-panel.js"
import "@awesome.me/webawesome/dist/components/switch/switch.js"
import "@awesome.me/webawesome/dist/components/tab-group/tab-group.js"
import "@awesome.me/webawesome/dist/components/tab-panel/tab-panel.js"
import "@awesome.me/webawesome/dist/components/tab/tab.js"
import "@awesome.me/webawesome/dist/components/tag/tag.js"
import "@awesome.me/webawesome/dist/components/textarea/textarea.js"
import "@awesome.me/webawesome/dist/components/tooltip/tooltip.js"
import "@awesome.me/webawesome/dist/components/tree-item/tree-item.js"
import "@awesome.me/webawesome/dist/components/tree/tree.js"
import "@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js"


export function render() {
    const input = JSON.parse(Host.inputString())

    const templ = input.content
    Host.outputString(renderString(templ))
}
